#server.port = 8081
server:
  port : 8081

logging:
  level:
    root: info

# 로컬 호스트 사용할 때 쓰는 코드
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      datasource:
        driver-class-name: com.mysql.jc.jdbc.Driver
        url: jdbc:mysql://localhost:3306/likelion-db
        username: root
        password: qwe123


# ec2 사용할 때 쓰는 코드
#SPRING_DATASOURCE_URL=jdbc:mysql://ec2-3-38-111-117:
#  ap-northeast-2:
#    compute:
#      amazonaws:
#        com:3306/likelion-db: