#server.port = 8081
server:
  port : 8081

logging:
  level:
    root: info

#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

spring:
  datasource:
    driver-class-name: com.mysql.jc.jdbc.Driver
    url: jdbc:mysql://localhost:3306/likelion-db
    username: root
    password: qwe123